export LAB_LOCATION="italynorth"
export LAB_SUFFIX="5a3d394d"
export LAB_RG="rg-cea-ud02-5a3d394d"
export LAB_VNET="vnet-cea-ud02"
export LAB_SUBNET="snet-app"
export LAB_STORAGE="stcea5a3d394d"
export LAB_DELETE_AFTER="$(date -d '+2 days' +%F)"